### ISSUE TITLE
Interface with unisat

### ISSUE THREAD

**Issue by donut33-social** [ziancube/ordinals-brc20-bitcoinjs#1]
Can you provide a sample code for how to mint a ordinals inscription with bitcoinjs and signed by unisat wallet in chrome? 
Thank you very much!

**Comment by ZXC-zxc** [comment]
It's a huge job, I haven't add this feature in our production,so there is no ready-made code.
But I think you can refer to some dapp code, make a PSBT use this code  and send to Unisat Wallet with it's signPsbt interface.
https://docs.unisat.io/dev/unisat-developer-service/unisat-wallet#signpsbt
